name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [20, 21]         # Only supported Node versions
        allow_failure: [false, true]  # For experimental runs
        include:
          - os: ubuntu-latest
            node: 21
            allow_failure: true   # Experimental job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with: 
          name: coverage-${{ matrix.os }}-node-${{ matrix.node }}
          path: coverage/
