name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code, this pulls my repo code on ubuntu machine and runs the code over there
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: package-lock.json

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run Linter
      - name: Run Linter
        run: npm run lint

      # 5. Run Tests
      - name: Run Tests
        run: npm test

      # 6. Upload coverage report as artifact
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with: 
          name: coverage-report
          path: coverage/
        
