name: Nodejs Demo of CI

on:
  push: 
    branches: 
      'main'
  pull_request: 
    branches: 
      "main"
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps: 
      #1: Checkout code
      - name: Checkout repository
        uses: actions/setup-node@v3
        
      #2: Setup Node.js
      - name: setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18
          cache: "npm"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install   

      # 4. Linting
      - name: Run Linter
        run: npm run lint
      
      # 5. Run Tests with Coverage
      - name: Run Tests
        run: npm test

      # 6. Upload test coverage report (artifact)
      # - name: Upload coverage report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: coverage-report
      #     path: coverage/