name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [16, 18, 20]
        experimental: [false, true, false]
        exclude: 
          - os: macos-latest
            node: 16
        include:
          - os: ubuntu-latest
            node: 21
            experimental: true

    steps:
      # 1. Checkout code, this pulls my repo code on ubuntu machine and runs the code over there
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: echo "Connecting to ${{ secrets.DATABASE_URL }}"

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run Linter
      # - name: Run Linter
      #   run: npm run lint

      # 5. Run Tests
      - name: Run Tests
        run: npm test

      # 6. Upload coverage report as artifact
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with: 
          name: coverage-report
          path: coverage/
      
    